app/urls.py
from django.conf.urls import url
from app import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^services/$', views.services, name='services'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^gallery/(?P<Album_id>[0-9]+)/$',views.photos,name='photos'),
]

studio/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Album(models.Model):
    name = models.CharField(max_length=200);
    image = models.FileField();
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.name

class Photo(models.Model):
    title = 'photo'
    grids = (('1','1'),('2','2'))
    image = models.FileField();
    pub_date = models.DateTimeField('date published')
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    grid = models.CharField(max_length=1,choices = grids,default = 1)

    def __str__(self):
        return self.title

app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Album,Photo

# Create your views here.
def home(request):
    return render(request,'site/index.html')

def about(request):
    return render(request,'site/about.html')

def services(request):
    return render(request,'site/services.html')

def gallery(request):
    album = Album.objects.order_by('-pub_date')
    context = {'album' : album}
    return render(request,'site/portfolio.html',context)

def contact(request):
    return render(request,'site/contact.html')
def photos(request,Album_id):
    album = Album.objects.get(pk = Album_id)
    return render(request, 'site/gallery.html',{'album': album,})

app/templates/site/about.html
{% extends 'site/base.html' %}
{% load staticfiles %}
{% block main_content %}
<header id="home_about">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 head">
				<h1 class="text-center">About</h1>
			</div>
		</div>
	</div>
</header>
<section id="about_about">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 about_about_head">
				<h3 class="text-center">About Imagi Studio</h3>
				<p class="text-center">nteger in odio ut velit laoreet mollis. </p>
				<hr>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 col-sm-12 about_about_holder">
				<p class="text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			</div>
		</div>
		<div class="row icon-holder">
			<div class="col-md-4 col-sm-4 text-center">
				<i class="fa fa-mobile icon" aria-hidden="true"></i>
				<h4>About Imagi Studio</h4>
				<p>lorem ipsum</p>
			</div>
			<div class="col-md-4 col-sm-4 text-center">
				<i class="fa fa-mobile icon" aria-hidden="true"></i>
				<h4>About Imagi Studio</h4>
				<p>lorem ipsum</p>
			</div>
			<div class="col-md-4 col-sm-4 text-center">
				<i class="fa fa-mobile icon" aria-hidden="true"></i>
				<h4>About Imagi Studio</h4>
				<p>lorem ipsum</p>
			</div>
		</div>
	</div>
</section>
<section id="about_team">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-6 more-base auto-height">
					<div class="more-abt">
							<h2>Meet our talented Team</h2>
					</div>
					<div class="more-sub">
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
					</div>
				</div>
				<div class="more-outer auto-height">
					<ul class="images">
						<li class="image"><img class="img-responsive" src="{% static 'img/10.jpg' %}" alt=""></li>
						<li class="image"><img class="img-responsive" src="{% static 'img/10.jpg' %}" alt=""></li>
						<li class="image"><img class="img-responsive" src="{% static 'img/10.jpg' %}" alt=""></li>
						<li class="image"><img class="img-responsive" src="{% static 'img/10.jpg' %}" alt=""></li>
						<li class="image"><img class="img-responsive" src="{% static 'img/10.jpg' %}" alt=""></li>
						<li class="image"><img class="img-responsive" src="{% static 'img/10.jpg' %}" alt=""></li>
					</ul>
				</div>
			</div>
		</div>
</section>
<section id="about_quotes">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<i class="fa fa-mobile icon" aria-hidden="true"></i>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
				<p><i>Author Name</i></p>
			</div>
		</div>
	</div>
</section>
{% endblock %}

app/templates/site/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Studio</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700|Source+Sans+Pro:200,400" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://use.fontawesome.com/be84370b8c.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.default.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body  data-spy="scroll" data-target=".navbar" data-offset="50">
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
			    <span class="sr-only">Toggle navigation</span>
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			  </button>
			  <a class="navbar-brand" href="#">STUDIO</a>
			</div>
			<div class="collapse navbar-collapse" id="navbar">
			  <ul class="nav navbar-nav navbar-right">
					{% with url_name=request.resolver_match.url_name %}
					<li class="{% if url_name == 'index' %}active{% endif %}" ><a href="/">Home</a></li>
			    <li class="{% if url_name == 'services' %}active{% endif %}" ><a href="/services">Services</a></li>
			    <li class="{% if url_name == 'about' %}active{% endif %}" ><a href="/about">About</a></li>
			    <li class="{% if url_name == 'gallery' %}active{% endif %}" ><a href="/gallery">Gallery</a></li>
					<li class="{% if url_name == 'live' %}active{% endif %}" ><a href="/gallery">Live</a></li>
			    <li class="{% if url_name == 'contact' %}active{% endif %}" ><a href="/contact">Contact</a></li>
					{% endwith %}
			  </ul>
			</div>
		</div>
	</nav>
  {% block main_content %}
  {% endblock %}
	<section id="footer">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-3">
					<h4>IMAGI STUDIO</h4>
				</div>
				<div class="col-md-3 col-sm-3">
					<h4>USEFULL LINKS</h4>
					<ul>
						<li><a href="#">About</a></li>
						<li><a href="#">Services</a></li>
						<li><a href="#">Gallery</a></li>
						<li><a href="#">Contact</a></li>
				</div>
				<div class="col-md-3 col-sm-3">
					<h4>ABOUT</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
				</div>
				<div class="col-md-3 col-sm-3 tags">
					<h4>TAGS</h4>
					<a href="#">about</a>
					<a href="#">photography</a>
					<a href="#">studio</a>
					<a href="#">about</a>
				</div>
			</div>
		</div>
	</section>
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-7"><p>© 2017 studio.in . All rights reserved.</p></div>
				<div class="col-md-5">
					<ul>
						<li><a href="#">Facebook</a></li>
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Youtube</a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="{% static 'scripts/owl.carousel.min.js' %}"></script>
	<script src="{% static 'scripts/numscroller-1.0.js' %}"></script>
	<script src="{% static 'scripts/typed.min.js' %}"></script>
	<script src="{% static 'scripts/jquery.matchHeight-min.js' %}"></script>
	<script src="{% static 'scripts/lightbox.min.js' %}"></script>
	<script src="{% static 'scripts/scripts.js' %}"></script>
</body>
</html>

app/templates/site/contact.html
{% extends 'site/base.html' %}
{% load staticfiles %}
{% block main_content %}
<header id="home_about">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 head">
				<h1 class="text-center">Contact Us</h1>
			</div>
		</div>
	</div>
</header>
<section id ="contact-form">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 contact_head">
				<h3 class="text-center">Get in touch with us</h3>
				<p class="text-center">nteger in odio ut velit laoreet mollis. </p>
				<hr>
			</div>
		</div>
	<div class="row">
		<div class="col-md-7">
			<h4 class="main-heading">CONTACT FORM</h4>
			<form method="post" class="row" id="contact_form" accept-charset="utf-8">
			<input type='hidden' name='csrfmiddlewaretoken' value='IPqBIvfr84t9S6WgwaLvaTVjfsRjg8BuNJdOyuhz3L8FMEX9zyKYO4FeOH1l2w2s' />
					<div class="col-md-6 input">
						<label >First Name</label>
						<input type="text" name="fname" class="form-control"  placeholder="First Name" required="true">
					</div>
					<div class="col-md-6 input">
						<label >Last Name</label>
						<input type="text" name="lname" class="form-control" placeholder="Last Name" required="true">
					</div>
					 <div class="col-md-6 input">
						<label >Email</label>
						<input type="text" name="email" class="form-control"  aria-describedby="emailHelp" placeholder="Email" required="true">
						<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
					</div>
						<div class="col-md-6 input">
						<label >Phone Number</label>
						<input type="text" name="pno" class="form-control"  placeholder="Phone Number" required="true">
					</div>
					<div class="col-md-12 input">
						<label >Write your message here</label>
						<textarea class="form-control" name="message" rows="6" required="true"></textarea>
					</div>
					<div class="col-md-12 input">
					<a id="submit" class="btn btn-primary form-button">SEND MESSAGE</a>

					<div  id="result" class="alert alert-danger" role="alert"><p ></p></div>
					</div>
				</form>
			</div>
		<div class="col-md-5">
			<div class="contact-details">
				<h3>IN TOUCH</h3>
				<hr>
				<h4>Location:</h4>
				<p>373 Main Street West</p>
				<p>Pikesville, MD 21208</p>
				<h4>EMAIL:</h4>
				<p>abc@studio.in</p>
				<h4>PHONE NUMBER:</h4>
				<p>+91 9995731234</p>
			</div>
		</div>
		</div>
	</div>
</section>
<section id="contact-map">
	<div class="container">
	<div class="row">
		<div class="col-md-12 text-center">
					 <h4 class="main-heading">VIEW US ON GOOGLE MAP</h4>
					 <p class="main-content">You can find us on google map<br>
											 </p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div id="map"></div>
		</div>
	</div>
</div>
</section>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAXYfg-eTUhPJV-vJsOG6WPbvwkbzEsSdU"></script>

			<script type="text/javascript">
					// When the window has finished loading create our google map below
					google.maps.event.addDomListener(window, 'load', init);

					function init() {
							// Basic options for a simple Google Map
							// For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
							var mapOptions = {
									// How zoomed in you want the map to start at (always required)
									zoom: 15,
									scrollwheel: false,

									// The latitude and longitude to center the map (always required)
									center: new google.maps.LatLng(9.0513177,76.5362767), // New York

									// How you would like to style the map.
									// This is where you would paste any style found on Snazzy Maps.
									styles: [{"featureType":"administrative","elementType":"all","stylers":[{"saturation":"-100"}]},{"featureType":"administrative.province","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"landscape","elementType":"all","stylers":[{"saturation":-100},{"lightness":65},{"visibility":"on"}]},{"featureType":"poi","elementType":"all","stylers":[{"saturation":-100},{"lightness":"50"},{"visibility":"simplified"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":"-100"}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.arterial","elementType":"all","stylers":[{"lightness":"30"}]},{"featureType":"road.local","elementType":"all","stylers":[{"lightness":"40"}]},{"featureType":"transit","elementType":"all","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"water","elementType":"geometry","stylers":[{"hue":"#ffff00"},{"lightness":-25},{"saturation":-97}]},{"featureType":"water","elementType":"labels","stylers":[{"lightness":-25},{"saturation":-100}]}]
							};

							// Get the HTML DOM element that will contain your map
							// We are using a div with id="map" seen below in the <body>
							var mapElement = document.getElementById('map');

							// Create the Google Map using our element and options defined above
							var map = new google.maps.Map(mapElement, mapOptions);

							// Let's also add a marker while we're at it
							var marker = new google.maps.Marker({
									position: new google.maps.LatLng(9.0513177, 76.5362767),
									map: map,
									title: 'Uniland Homes'
							});
					}

			</script>
{% endblock %}

app/templates/site/gallery.html
{% extends 'site/base.html' %}
{% load staticfiles %}
{% block main_content %}
<header id="home_about">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 head">
				<h1 class="text-center">Gallery</h1>
			</div>
		</div>
	</div>
</header>
<section id="about_about">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<h3 class="text-center">A Portfolio Masonry Boxed</h3>
				<p class="text-center">Donec ornare, libero ultrices dictum pharetra, diam justo auctor orci. </p>
				<hr>
			</div>
		</div>
	</div>
</section>
<section id="portfolio">
	<div class="container-fluid">
		<div class="row gallery">
			<div class="col-md-6 images">
			{% for photo in album.photo_set.all %}
				{% if photo.grid == '1'%}
					<div class="image">
							<img class="img-responsive" src="{{ photo.image.url }}" alt="">
						<div class="datas">
							<p class="text-center"><i class="fa fa-search-plus icon" aria-hidden="true"></i><br>La Cervecita</p>
						</div>
					</div>
				{% endif %}
				{% endfor %}
			</div>
			<div class="col-md-6 images">
			{% for photo in album.photo_set.all %}
				{% if photo.grid == '2'%}
					<div class="image">
						<img class="img-responsive" src="{{ photo.image.url }}" alt="">
						<div class="datas">
							<p class="text-center"><i class="fa fa-search-plus icon" aria-hidden="true"></i><br>La Cervecita</p>
						</div>
					</div>
				{% endif %}
				{% endfor %}
			</div>
		</div>
	</div>
</section>
{% endblock %}

app/templates/site/index.html
{% extends 'site/base.html' %}
{% load staticfiles %}
{% block main_content %}
<header id="home">
  <div class="owl-carousel main_slider">
      <div class="item">
          <img src="{% static 'img/bg.jpg' %}" alt="" class="slide-bg">
          <div class="row m0 slide_caption">
              <div class="container">
                  <div class="row">
                      <div class="col-sm-6">
                          <div class="row m0 caption_iiner">
                              <h2 class="first_heading">We are</h2>
                              <h3 class="second_heading">STUDIO</h3>
                              <h5 class="fourth_heading">Lorem ipsunm dolor sit amet</h5>
                              <p>This is our portfolio. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam ahoncus</p>
                          </div>
                      </div>
                  </div>
              </div>
          </div> <!--Caption Container-->
      </div>
      <div class="item">
          <img src="{% static 'img/bg.jpg' %}" alt="" class="slide-bg">
          <div class="row m0 slide_caption">
              <div class="container">
                  <div class="row">
                      <div class="col-sm-6">
                          <div class="row m0 caption_iiner">
                              <h2 class="first_heading">We are</h2>
                              <h3 class="second_heading">STUDIO</h3>
                              <h5 class="fourth_heading">Lorem ipsunm dolor sit amet</h5>
                              <p>This is our portfolio. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam ahoncus</p>
                          </div>
                      </div>
                  </div>
              </div>
          </div> <!--Caption Container-->
      </div>
      <div class="item">
          <img src="{% static 'img/bg.jpg' %}" alt="" class="slide-bg">
          <div class="row m0 slide_caption">
              <div class="container">
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="row m0 caption_iiner">
                              <br><br><br><br>
                              <h4 class="third_heading">We make your life beautiful</h4>
                              <h4 class="third_heading">We are <strong>STUDIO</strong></h4>
                          </div>
                      </div>
                  </div>
              </div>
          </div> <!--Caption Container-->
      </div>
  </div>
  <div class="row m0 mouse_button">
      <div class="container">
          <a href="#services" class="goTo_severces"><img src="{% static 'img/mouse2.png' %}" alt="" id="mouse"></a>
      </div>
  </div>
</header>
<section id="about">
  <div class="container-fluid">
    <div class="col-sm-12 about-head">
      <h1 class="text-center"><span style="color: var(--primary-color)">IMAGI</span> STUDIO - OVERVIEW</h1>
    </div>
    <div class="col-sm-12 about-holder text-center">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
  </div>
</section>
<section id="services">
  <div class="container-fluid">
    <div class="row item-holder">
      <div class="col-md-4 col-sm-4 text-center items border-top-none">
        <i class="fa fa-desktop icon" aria-hidden="true"></i>
        <h5>Responsive Websites</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. </p>
      </div>
      <div class="col-md-4 col-sm-4 text-center items border-top-none">
        <i class="fa fa-mobile icon" aria-hidden="true"></i>
        <h5>Android Apps</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. </p>
      </div>
      <div class="col-md-4 col-sm-4 text-center items border-right-none border-top-none">
        <i class="fa fa-phone icon" aria-hidden="true"></i>
        <h5>Great Support</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. </p>
      </div>
    </div>
    <div class="row item-holder">
      <div class="col-md-4 col-sm-4 text-center items">
        <i class="fa fa-pencil icon" aria-hidden="true"></i>
        <h5>Design</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. </p>
      </div>
      <div class="col-md-4 col-sm-4 text-center items">
        <i class="fa fa-bar-chart icon" aria-hidden="true"></i>
        <h5>Marketting</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. </p>
      </div>
      <div class="col-md-4 col-sm-4 text-center items border-right-none">
        <i class="fa fa-calendar icon" aria-hidden="true"></i>
        <h5>Schedule</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. </p>
      </div>
    </div>
  </div>
</section>
<section id="moreinfo">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6 col-sm-6 more-base">
          <div class="more-abt">
              <h2>CREATIVE AGENCY</h2>
          </div>
          <div class="more-sub">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <button type="button" name="button">LEARN MORE</button>
          </div>
        </div>
        <div class="col-md-6 col-sm-6 more-outer">

        </div>
      </div>
    </div>
</section>
<section id="portfolio">
  <div class="container contents">
    <div class="row">
      <div class="head col-md-12 text-center">
        <h2 class="heading">MEET YOUR DREAM</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 items">
        <div class="owl-carousel owl-theme">
          <div class="item"><img class="port img-responsive" src="{% static 'img/bg-header.jpg' %}"></div>
          <div class="item"><img class="img-responsive" src="{% static 'img/bg-header.jpg' %}"></div>
          <div class="item"><img class="img-responsive" src="{% static 'img/bg-header.jpg' %}"></div>
          <div class="item"><img class="img-responsive" src="{% static 'img/bg-header.jpg' %}"></div>
          <div class="item"><img class="img-responsive" src="{% static 'img/bg-header.jpg' %}"></div>
          <div class="item"><img class="img-responsive" src="{% static 'img/bg-header.jpg' %}"></div>
          <div class="item"><img class="img-responsive" src="{% static 'img/bg-header.jpg' %}"></div>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="email">
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-sm-9">
        <h3>WANT TO WORK WITH US?</h3>
        <p>Integer in odio ut velit laoreet mollis. Sed elementum sit amet dolor pulvinar ornare.<br>
          Aliquam sit amet leo placerat, accumsan elit ut, ultrices urna.</p>
      </div>
      <div class="col-md-3 col-s-3">
        <button type="button" class="btn btn-default" name="button">EMAIL US</button>
      </div>
    </div>

  </div>
</section>
{% endblock %}

app/templates/site/portfolio.html
{% extends 'site/base.html' %}
{% load staticfiles %}
{% block main_content %}
<header id="home_about">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 head">
				<h1 class="text-center">Gallery</h1>
			</div>
		</div>
	</div>
</header>
<section id="about_about">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<h3 class="text-center">A Portfolio Masonry Boxed</h3>
				<p class="text-center">Donec ornare, libero ultrices dictum pharetra, diam justo auctor orci. </p>
				<hr>
			</div>
		</div>
	</div>
</section>
<section id="portfolio">
	<div class="container-fluid">
		<div class="row gallery">
			{% for photo in album %}
			<div class="col-md-4 images">
					<a href="{% url 'photos' photo.id %}"><div class="image">
							<img class="img-responsive" src="{{ photo.image.url }}" alt="">
						<div class="datas">
							<p class="text-center"><br>{{ photo.name }}</p>
						</div>
					</div></a>
			</div>
			{% endfor %}
		</div>
	</div>
</section>
{% endblock %}